
max-output-size-K: 137

# Default is false, but include it anyway
batch_testcases_on_event_feed: false

wf_honors_ranking: false

sites:
 - number: 1
   name: Site 1
   IP: localhost
   port: 50002

accounts:
  - account: TEAM
    site: 1
    count: 22

  - account: JUDGE
    site: 1
    count: 12

  - account: SCOREBOARD
    site: 1
    count: 2

  - account: FEEDER
    site: 1
    count: 1

# enable perms for FEEDER 1 to edit runs and submit runs
permissions:
  - account: FEEDER
    number: 1
    enable: SHADOW_PROXY_TEAM, EDIT_RUN, START_CONTEST_CLOCK, STOP_CONTEST_CLOCK
    
auto-judging:
  - account: JUDGE
    site: 1
    number: 3
    letters: A, B
    enabled: yes

  - account: JUDGE
    site: 1
    number: 4
    letters: A, B
    enabled: yes

  - account: JUDGE
    site: 1
    number: 5
    letters: B
    enabled: yes

# pc2 Shadow CCS settings
shadow-mode: false
ccs-test-mode : true

# EOF Contest Configuration
