#!/bin/sh
#
# Purpose: Start the EWU Java Bridge/Server
# Author : pc2@ecs.csus.edu
# $HeadURL$
#

. `dirname $0`/ewenv

# MacOS or not
if [ -f /mach_kernel ]; then
  # set our dock name (otherwise defaults to Starter)
  EWUOPTS="-Xdock:name=`basename $0`"
else
  EWUOPTS=""
fi

java $EWUOPTS -Xms64M -Xmx1600M -cp $libdir/pc2.jar -jar $libdir/PC2JavaServer.jar $*

# ewrun $Id$
