#!/bin/csh
#
# File:    compilePerl
# Purpose: Used to compile/use Perl with PC^2
# Author:  pc2@ecs.csus.edu
#
# Dependencies:  perl 
#
# pc2 language settings:
# 
# Display Name                       : Perl
# Compile Command Line               : compilePerl {:mainfile} 
# Executable Filename specification  : OK 
# Program Execution Command Line     : perl {:mainfile}
#
# $HeadURL$
#

perl -c $*

if ($? == 0) then
    touch OK
endif 

# eof compilePerl $Id$
