#!/bin/sh
#
# Purpose: run API ServerConnection 
#
# Author : pc2@ecs.csus.edu
# $HeadURL$
#

. `dirname $0`/pc2env

java  -Xms64M -Xmx768M -cp $libdir/pc2.jar edu.csus.ecs.pc2.api.ServerConnection $*

# eof pc2nc $Id$ 
