// Copyright (C) 1989-2025 PC2 Development Team: John Clevenger, Douglas Lane, Samir Ashoo, and Troy Boudreau.
package edu.csus.ecs.pc2.clics.API202306;

import java.io.IOException;

import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;

import edu.csus.ecs.pc2.core.Constants;

/**
 * @author John Buck
 *
 */
public class SubmitPostSizeLimitFilter implements ContainerRequestFilter {

    // Calculate approximate size of non-source code json overhead for a submit.  A typical submission
    // json packet looks like this (generated by pc2submit):
    // {"problem_id": "hello", "language_id": "python3", "files": [{"data": "<base64-data-source-file>", "filename": "hello.cpp"}]}
    // 123456789012345678901234567890123456789012345678901234567890123456.........................789012345678901234567890123456789
    //          1         2         3         4         5         6                                  7         8         9
    // So, it uses 99 chars for the example above.  We have to add some elbow room in too for longer problem ids since
    // the example was for "hello".  We assume a maximum problem name of 32 chars.  It's not a huge deal if the
    // problem id is > 32, we'll just short-change the submitted source code by that many bytes.  Listen, if you're submitting
    // code that is 256KB, you get what you deserve.
    //
    private static long SUBMIT_MAX_PROBLEM_ID_LEN = 32;
    // Length of "hello" above.
    private static long SAMPLE_JSON_PROBLEM_ID_LEN = 5;
    private static long SUBMIT_JSON_OVERHEAD_BYTES = 99 + 2*SUBMIT_MAX_PROBLEM_ID_LEN - 2*SAMPLE_JSON_PROBLEM_ID_LEN;
    // Configured value for max source length
    private static long maxSourceSizeBytes = Constants.DEFAULT_MAX_SOURCE_SIZE_K * 1024;
    // Must account for base64 encoding which adds encodes 3 bytes as 4, eg. multiply by 4/3 and round up
    private static long maxSubmitPostSizeBytes = SUBMIT_JSON_OVERHEAD_BYTES + (maxSourceSizeBytes * 4 + 2)/3;

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        if (requestContext.getMethod().equalsIgnoreCase("POST")) {
            UriInfo uInfo = requestContext.getUriInfo();
            String relPath = uInfo.getPath();
            if(relPath.endsWith("/submissions")) {
                long contentLength = requestContext.getLength();
                // we test maxSourceSizeBytes being > 0 here and NOT maxSubmitPostSizeBytes.
                // if maxSourceSizeBytes is 0, then there is no limit on the source size.
                // maxSubmitPostSizeBytes will always be non-zero, since it contains the overhead
                // of the json.  We DO want to use maxSubmitPostSizeBytes to compare against
                // contestLength since that includes the overhead.
                if (maxSourceSizeBytes > 0 && contentLength > maxSubmitPostSizeBytes) {
                    requestContext.abortWith(Response.status(Response.Status.REQUEST_ENTITY_TOO_LARGE)
                            .entity("Submission too large. Maximum allowed size is " + maxSourceSizeBytes + " bytes.")
                            .build());
                }
            }
        }
    }

    /**
     * The max post size is different than the max source size.
     * The post size includes json overhead and the base64 encoding, so, account for that here.
     *
     * @param maxSourceBytes
     */
    public static void setMaxSubmitPostSizeBytes(long maxSourceBytes) {
        maxSourceSizeBytes = maxSourceBytes;
        maxSubmitPostSizeBytes = SUBMIT_JSON_OVERHEAD_BYTES + (maxSourceSizeBytes * 4 + 2)/3;
    }
}
