#!/bin/sh
# Copyright (C) 1989-2020 PC2 Development Team: John Clevenger, Douglas Lane, Samir Ashoo, and Troy Boudreau.
#
# Purpose: start the Web Team Interface (WTI) project Web Team Server
# Author : pc2@ecs.csus.edu
#

# MacOS or not
if [ -f /mach_kernel ]; then
  # set our dock name (otherwise defaults to Starter)
  PC2XOPS="-Xdock:name=`basename $0`"
else
  PC2XOPS=""
fi

java -Djdk.crypto.KeyAgreement.legacyKDF=true $PC2XOPS -Xms64M -Xmx2048M -jar WebTeamInterface-1.1.jar

# eof pc2wti 
