#!/bin/sh
# Copyright (C) 1989-2020 PC2 Development Team: John Clevenger, Douglas Lane, Samir Ashoo, and Troy Boudreau.
#
# Purpose: start the ZipWTI to archive WTI files
# Author : Douglas A. Lane <pc2@ecs.csus.edu>
#

# MacOS or not
if [ -f /mach_kernel ]; then
  # set our dock name (otherwise defaults to Starter)
  PC2XOPS="-Xdock:name=`basename $0`"
else
  PC2XOPS=""
fi

java -Djdk.crypto.KeyAgreement.legacyKDF=true -Xms64M -Xmx2048M -cp WebTeamInterface-1.1.jar edu.csus.ecs.pc2.wti.core.archive.ZipWTI %1 %2 %3 %4 %5 %6 %7 %8 %9 

# eof pc2wti 
