#!/bin/sh
#
# Purpose: Start the EW Java Bridge/Server
# Author : pc2@ecs.csus.edu
#

echo ""
echo "Warning: EWTeam is deprecated and will be removed in an upcoming version of PC^2."
echo "It has been superseded by the "Web Team Interface (WTI)" project;"
echo "  see Appendix N in the PC^2 Contest Administrator's Guide for details on using WTI as a web-based interface for teams."
echo ""

. `dirname $0`/ewenv

# MacOS or not
if [ -f /mach_kernel ]; then
  # set our dock name (otherwise defaults to Starter)
  EWOPTS="-Xdock:name=`basename $0`"
else
  EWOPTS=""
fi

java $EWOPTS -Djdk.crypto.KeyAgreement.legacyKDF=true -Xms64M -Xmx1600M -cp $libdir/pc2.jar -jar $libdir/PC2JavaServer.jar $*

# eof ewrun  
