#
# Contest configuration 
# Based on CCS Spec contest.yaml
#
---
name:              ACM-ICPC CLI CCS Sample One
short-name:        ICPC WF 2011
start-time:        2060-02-04 01:23Z
duration:          5:00:00
scoreboard-freeze: 4:00:00

output-private-score-dir: super_secret
output-public-score-dir: public_html_dir

auto-stop-clock-at-end: true
memory-limit-in-Meg: 8086

sandbox: 'linux_sandbox --verbose'

default-clars:
  - No comment, read problem statement.
  - This will be answered during the answers to questions session.

clar-categories:
  - General
  - SysOps
  - Operations

languages:
  - name: C++
    compiler: /usr/bin/g++  
    compiler-args: -O2 -Wall -o a.out -static {files} 

  - name: C
    compiler: /usr/bin/gcc
    compiler-args: -O2 -Wall -std=gnu99 -o a.out -static {files} -lm
  
  - name: Java
    compiler: /usr/bin/javac
    compiler-args: -O {files}
    runner: /usr/bin/java
    runner-args: 

problemset:
  - letter:     A
    short-name: apl
    color:      yellow
    rgb:        #ffff00
  
  - letter:     B
    short-name: barcodes
    color:      red
    rgb:        #ff0000
  
  - letter:     C
    short-name: biobots
    color:      green
    rgb:        #00ff00
  
  - letter:     D
    short-name: castles
    color:      blue
    rgb:        #0000ff
  
  - letter:     E
    short-name: channel
    color:      white
    rgb:        #ffffff

# eof 
