package WebsocketEnums;

public enum WebsocketMsgType {
	UNDEFINED, JUDGED, CONTEST_CLOCK, TEST, CLARIFICATION, REFRESH_RUNS_LIST, REFRESH_CLARIFICATION_LIST, ANNOUNCEMENT, STANDINGS, CONNECTION_DROPPED
}
