// Copyright (C) 1989-2019 PC2 Development Team: John Clevenger, Douglas Lane, Samir Ashoo, and Troy Boudreau.

package edu.csus.ecs.pc2.shadow;

import java.util.Map;

/**
 * This class encapsulates the configuration of a contest language from a remote CCS, as
 * described by the Map provided to its constructor.
 * 
 * Typically the provided Map will have been generated by fetching a JSON string from the 
 * remote CCS "/languages" endpoint, constructing a Map from each element (language) in that
 * JSON string, and passing that Map to this class's constructor, creating one new RemoteLanguageConfiguration
 * object for each language in the JSON returned from the remote CCS.
 * 
 * @author John Clevenger, PC2 Development Team (pc2@ecs.csus.edu)
 *
 */
public class RemoteLanguageConfiguration extends AbstractRemoteConfigurationObject {

    /**
     * Constructs a RemoteLanguageConfiguration object with 
     * REMOTE_CONFIGURATION_ELEMENT type "CONFIG_LANGUAGES" and with the
     * specified Map of problem keywords and corresponding values.
     * 
     * @param configurationValues a Map mapping the language element keywords to corresponding values
     */
    public RemoteLanguageConfiguration(Map<String, String> configurationValues) {
        super(IRemoteContestAPIAdapter.REMOTE_CONFIGURATION_ELEMENT.CONFIG_LANGUAGES, configurationValues);
    }

}
