// Copyright (C) 1989-2019 PC2 Development Team: John Clevenger, Douglas Lane, Samir Ashoo, and Troy Boudreau.

package edu.csus.ecs.pc2.shadow;

import java.util.Map;

/**
 * This class encapsulates the configuration of a contest problem from a remote CCS, as
 * described by the Map provided to its constructor.
 * 
 * Typically the provided Map will have been generated by fetching a JSON string from the 
 * remote CCS "/problems" endpoint, constructing a Map from each element (problem) in that
 * JSON string, and passing that Map to this class's constructor, creating one new RemoteProblemConfiguration
 * object for each problem in the JSON returned from the remote CCS.
 * 
 * @author John Clevenger, PC2 Development Team (pc2@ecs.csus.edu)
 *
 */
public class RemoteProblemConfiguration extends AbstractRemoteConfigurationObject {

    /**
     * Constructs a RemoteProblemConfiguration object with 
     * REMOTE_CONFIGURATION_ELEMENT type "CONFIG_PROBLEMS" and with the
     * specified Map of problem keywords and corresponding values.
     * 
     * @param configurationValues a Map mapping the problem element keywords to corresponding values
     */
    public RemoteProblemConfiguration(Map<String, String> configurationValues) {
        super(REMOTE_CONFIGURATION_ELEMENT.CONFIG_PROBLEMS, configurationValues);
    }

}
