import { Pipe, PipeTransform } from '@angular/core';

//coded generated by Google AI
//Explanation:
//The pipe takes a Date or a timestamp as input.
//It calculates the difference in milliseconds between the given date and the current time.
//Then, it extracts days, hours, minutes, and seconds from the difference.
//Finally, it formats the output string.

@Pipe({
  name: 'elapsedTime'
})
export class ElapsedTimePipe implements PipeTransform {

  transform(value: Date | number): string {
    const now = new Date().getTime();
    const then = new Date(value).getTime();

    const diff = now - then;

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((diff % (1000 * 60)) / 1000);

    return `${days}d ${hours}h ${minutes}m ${seconds}s`;
  }
}