import { Pipe, PipeTransform } from '@angular/core';

//This class defines a "pipe" which accepts a "Date" object and returns 
// a formatted string representing the number of days/hours/minutes/seconds that have 
// elapsed between the specified Date and "now".
//The "pipe" is suitable for use, for example, in an Angular HTML template (see app-header.component.html).
//It is based on code generated by Google AI.

//It calculates the difference in milliseconds between the given date and the current time.
//Then it extracts days, hours, minutes, and seconds from the difference.
//Finally, it formats the output string.  "Days" are only included in the output if they are greater than zero.

@Pipe({
  name: 'elapsedTime',
  standalone: true
})
export class ElapsedTimePipe implements PipeTransform {

   /**
	Returns a string representing the elapsed time between the input Date and "now".
    */
  transform(startDate: Date): string {
    const now = new Date().getTime();
    const then = startDate.getTime();

    const diff = now - then;

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((diff % (1000 * 60)) / 1000);

    const formattedHours = hours.toString().padStart(2, '0');
    const formattedMinutes = minutes.toString().padStart(2, '0');
    const formattedSeconds = seconds.toString().padStart(2, '0');

  
	if (days > 0) {
		return `${days}d ${formattedHours}:${formattedMinutes}:${formattedSeconds}`;
	} else {
		return `${formattedHours}:${formattedMinutes}:${formattedSeconds}`;
	}

  }
}